### ISSUE TITLE
Add prefixing functionality

### ISSUE THREAD

**Issue by robertDurst** [robertDurst/stellar-vanity-address-generator#2]

**Comment by charlie-wasp** [comment]
I would like to help with it 🙋‍♂

**Comment by robertDurst** [comment]
Awesome! Let me know if you run into any trouble or need some help figuring out where to begin?

**Comment by charlie-wasp** [comment]
At the moment I'm trying to update dependencies and build the project 😅 Because some dependencies were yanked from crates.io, and in the current versions APIs were changed

**Comment by robertDurst** [comment]
Oh my, sorry about that! Has been a few days... or well months since I updated the dependencies.

**Comment by robertDurst** [comment]
Any api changes breaking change significant?

**Comment by charlie-wasp** [comment]
I believe, no, just some permutations in `rand` crate's modules. I'll try to fix that and open PR

**Comment by charlie-wasp** [comment]
Some API has been changed, actually, but nothing massive. Here is PR — #3

**Comment by robertDurst** [comment]
Thanks for that! Looks good, merged and opened an [issue to update the crate version and push to crates.io](https://crates.io/search?q=stellar) which I will tackle tonight.

Fun fact, this is the most downloaded Stellar crate now...

**Comment by robertDurst** [comment]
Sweet!
