### ISSUE TITLE
Parallelize account generation

### ISSUE THREAD

**Issue by robertDurst** [robertDurst/stellar-vanity-address-generator#7]
Allow for someone to specify a given number of threads:

`cargo run <PREFIX> --threads=<THREADS>`

and run this process in parallel.

This should be an optional flag, defaulting to just one (current functionality).

**Comment by charlie-wasp** [comment]
I would like to give it a shot! 🙋‍♂

**Comment by robertDurst** [comment]
Awesome @charlie-wasp ! What's your plan of attack?

**Comment by charlie-wasp** [comment]
Well, at first I need to read about concurrency in Rust 😅 Overall plan, I think, would be having one supervisor thread, which spawns as many parallel threads as needed with the pipes open to them. The supervisor listen to all pipes, and as soon as there is a keypair, it  kills all the children and returns the found keypair

**Comment by robertDurst** [comment]
Yeah... I don't really have much knowledge about Rust's concurrency story either lol
