### ISSUE TITLE
Remove all dependencies

### ISSUE THREAD

**Issue by robertDurst** [robertDurst/stellar-vanity-address-generator#9]
This is quite a long term goal, and even one that is rather unnecessary... NEVER EVER ROLL YOUR OWN CRYPTO!!!!
![No!](https://media.giphy.com/media/kE8bAdv1AKdSqJf2Rw/giphy.gif)

Nevertheless, it would be cool to have written the entirety of this app from scratch.

**Comment by charlie-wasp** [comment]
Do you want to implement keypair generation in this lib?

**Comment by robertDurst** [comment]
Possibly -- I guess the gist of this is that I originally thought this would be cool as I wrote this for educational reasons related to cryptography. However, if anyone is to actually use this, it is a bit nonsensical to rewrite much of the crypto just to do it ourselves.

**Comment by robertDurst** [comment]
Not necessary, especially now that this may actually be useful there is no reason to redo the work of the Dalek wizards
